# default
spring:
  profiles:
    active: local

server.port: 3000
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/ikwydlnitus?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  properties:
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
  jpa:
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
      ddl-auto: update

  batch:
    job:
      names: sendNewsJob
      enabled: false
    jdbc:
      initialize-schema: ALWAYS



slack:
  bot-token:
  secret: