# default
spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/ikwydlnitus
    driver-class-name: org.postgresql.Driver
    username: root
    password: 1234

  properties:
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
  jpa:
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
